from __future__ import annotations

import json
import os
import re
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any
import logging
import src.logging_config  # ensure logging configured
from src.llm_service import get_llm_service

logger = logging.getLogger(__name__)


class LocalDataStore:
    def __init__(self, base_dir: str | Path | None = None):
        self.base_dir = Path(base_dir) if base_dir else Path(__file__).resolve().parent.parent
        self.data_dir = self.base_dir / "data"
        self.data_dir.mkdir(parents=True, exist_ok=True)

        self.employees_path = self.data_dir / "employees.json"
        self.knowledge_base_path = self.data_dir / "knowledge_base.json"
        self.tickets_path = self.data_dir / "tickets.json"
        self.system_status_path = self.data_dir / "system_status.json"
        self.db_path = self.data_dir / "it_support.db"

        self._initialize_db()
        self._seed_from_json_files()
        logger.info("LocalDataStore initialized with DB at %s", self.db_path)

    def _get_connection(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _safe_sql_with_llm(self, user_query: str, table_name: str | None = None) -> list[dict[str, Any]]:
        """Optional LLM-backed SQL path for reads. Must be explicitly enabled by env vars."""
        if os.getenv("USE_LLM_SQL", "false").lower() != "true":
            return []

        schema = {
            "employees": ["employee_id", "name", "department", "email", "role"],
            "tickets": ["ticket_id", "employee_id", "title", "description", "status", "category", "severity", "created_at", "updated_at"],
            "ticket_comments": ["id", "ticket_id", "employee_id", "comment", "created_at"],
            "ticket_events": ["id", "ticket_id", "event_type", "details", "created_at"],
            "system_status": ["system_name", "status", "notes"],
            "knowledge_base": ["id", "title", "keywords", "content"],
        }

        if table_name:
            schema = {table_name: schema.get(table_name, [])}

        llm_service = get_llm_service(provider=os.getenv("LLM_PROVIDER", "openai"))
        generated_sql = llm_service.generate_sql_query(user_query, schema)

        if not generated_sql.lower().startswith("select"):
            raise ValueError("LLM-generated SQL must begin with SELECT.")

        if any(disallowed in generated_sql.lower() for disallowed in ["insert", "update", "delete", "drop", "alter", "create", "grant", "revoke", "attach", "detach"]):
            raise ValueError("Unsafe SQL generated by LLM.")

        with self._get_connection() as conn:
            rows = conn.execute(generated_sql).fetchall()

        return [dict(row) for row in rows]

    def _initialize_db(self) -> None:
        logger.debug("Initializing local SQLite database at %s", self.db_path)
        with self._get_connection() as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS employees (
                    employee_id TEXT PRIMARY KEY,
                    name TEXT NOT NULL,
                    department TEXT,
                    email TEXT,
                    role TEXT DEFAULT 'employee'
                )
                """
            )
            employee_columns = [row["name"] for row in conn.execute("PRAGMA table_info(employees)").fetchall()]
            if "role" not in employee_columns:
                conn.execute("ALTER TABLE employees ADD COLUMN role TEXT DEFAULT 'employee'")

            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS knowledge_base (
                    id TEXT PRIMARY KEY,
                    title TEXT NOT NULL,
                    keywords TEXT,
                    content TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS tickets (
                    ticket_id TEXT PRIMARY KEY,
                    employee_id TEXT NOT NULL,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL,
                    status TEXT NOT NULL,
                    category TEXT,
                    severity TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                )
                """
            )
            existing_ticket_columns = [row["name"] for row in conn.execute("PRAGMA table_info(tickets)").fetchall()]
            if "updated_at" not in existing_ticket_columns:
                conn.execute("ALTER TABLE tickets ADD COLUMN updated_at TEXT")
                conn.execute(
                    "UPDATE tickets SET updated_at = created_at WHERE updated_at IS NULL OR updated_at = ''"
                )

            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS system_status (
                    system_name TEXT PRIMARY KEY,
                    status TEXT NOT NULL,
                    notes TEXT NOT NULL
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS ticket_events (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ticket_id TEXT NOT NULL,
                    event_type TEXT NOT NULL,
                    details TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    FOREIGN KEY (ticket_id) REFERENCES tickets(ticket_id)
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS ticket_comments (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ticket_id TEXT NOT NULL,
                    employee_id TEXT NOT NULL,
                    comment TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    FOREIGN KEY (ticket_id) REFERENCES tickets(ticket_id)
                )
                """
            )

    def _seed_from_json_files(self) -> None:
        logger.debug("Seeding database from JSON files in %s", self.data_dir)
        with self._get_connection() as conn:
            if conn.execute("SELECT COUNT(*) FROM employees").fetchone()[0] == 0:
                for employee in self._load_json_file(self.employees_path):
                    conn.execute(
                        "INSERT INTO employees (employee_id, name, department, email, role) VALUES (?, ?, ?, ?, ?)",
                        (
                            str(employee.get("employee_id", "")).upper(),
                            employee.get("name", ""),
                            employee.get("department", ""),
                            employee.get("email", ""),
                            employee.get("role", "employee").lower(),
                        ),
                    )
            else:
                for employee in self._load_json_file(self.employees_path):
                    conn.execute(
                        "UPDATE employees SET name = ?, department = ?, email = ?, role = ? WHERE employee_id = ?",
                        (
                            employee.get("name", ""),
                            employee.get("department", ""),
                            employee.get("email", ""),
                            employee.get("role", "employee").lower(),
                            str(employee.get("employee_id", "")).upper(),
                        ),
                    )

            if conn.execute("SELECT COUNT(*) FROM knowledge_base").fetchone()[0] == 0:
                for article in self._load_json_file(self.knowledge_base_path):
                    conn.execute(
                        "INSERT INTO knowledge_base (id, title, keywords, content) VALUES (?, ?, ?, ?)",
                        (
                            article.get("id", ""),
                            article.get("title", ""),
                            json.dumps(article.get("keywords", [])),
                            article.get("content", ""),
                        ),
                    )

            if conn.execute("SELECT COUNT(*) FROM tickets").fetchone()[0] == 0:
                for ticket in self._load_json_file(self.tickets_path):
                    created_at = ticket.get("created_at", datetime.utcnow().isoformat(timespec="seconds"))
                    updated_at = ticket.get("updated_at", created_at)
                    conn.execute(
                        """
                        INSERT INTO tickets (ticket_id, employee_id, title, description, status, category, severity, created_at, updated_at)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        (
                            ticket.get("ticket_id", ""),
                            str(ticket.get("employee_id", "")).upper(),
                            ticket.get("title", ""),
                            ticket.get("description", ""),
                            ticket.get("status", "Open"),
                            ticket.get("category", "General"),
                            ticket.get("severity", "Medium"),
                            created_at,
                            updated_at,
                        ),
                    )

            if conn.execute("SELECT COUNT(*) FROM system_status").fetchone()[0] == 0:
                for system in self._load_json_file(self.system_status_path):
                    conn.execute(
                        "INSERT INTO system_status (system_name, status, notes) VALUES (?, ?, ?)",
                        (
                            system.get("system_name", "Unknown"),
                            system.get("status", "Unknown"),
                            system.get("notes", ""),
                        ),
                    )

    def _load_json_file(self, file_path: Path) -> list[dict[str, Any]]:
        if not file_path.exists():
            logger.debug("JSON seed file not found: %s", file_path)
            return []
        with file_path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, list) else []

    def get_employee(self, employee_id: str | None) -> dict[str, Any] | None:
        if not employee_id:
            return None

        if os.getenv("USE_LLM_SQL", "false").lower() == "true":
            llm_query = f"Find employee record for employee_id = '{employee_id.upper()}'"
            rows = self._safe_sql_with_llm(llm_query, "employees")
            if rows:
                row = rows[0]
                return {
                    "employee_id": row.get("employee_id"),
                    "name": row.get("name"),
                    "department": row.get("department"),
                    "email": row.get("email"),
                    "role": row.get("role"),
                }

        with self._get_connection() as conn:
            row = conn.execute(
                "SELECT employee_id, name, department, email, role FROM employees WHERE employee_id = ?",
                (employee_id.upper(),),
            ).fetchone()

        if row is None:
            logger.debug("Employee not found: %s", employee_id)
            return None
        return {
            "employee_id": row["employee_id"],
            "name": row["name"],
            "department": row["department"],
            "email": row["email"],
            "role": row["role"],
        }

    def list_employees(self) -> list[dict[str, Any]]:
        with self._get_connection() as conn:
            rows = conn.execute("SELECT employee_id, name, department, email, role FROM employees ORDER BY employee_id").fetchall()
        return [
            {
                "employee_id": row["employee_id"],
                "name": row["name"],
                "department": row["department"],
                "email": row["email"],
                "role": row["role"],
            }
            for row in rows
        ]

    def search_knowledge(self, query: str) -> list[dict[str, Any]]:
        normalized_query = re.split(r"[^a-z0-9]+", query.lower())
        tokens = [token for token in normalized_query if len(token) > 2]
        if not tokens:
            return []

        with self._get_connection() as conn:
            rows = conn.execute("SELECT id, title, keywords, content FROM knowledge_base").fetchall()

        matches: list[dict[str, Any]] = []
        for row in rows:
            title = str(row["title"]).lower()
            content = str(row["content"]).lower()
            keywords_text = str(row["keywords"] or "[]").lower()
            combined = f"{title} {content} {keywords_text}"
            score = sum(1 for token in tokens if token in combined)
            if score > 0:
                matches.append(
                    {
                        "id": row["id"],
                        "title": row["title"],
                        "summary": row["content"][:220],
                        "match_score": score,
                    }
                )

        matches.sort(key=lambda item: item["match_score"], reverse=True)
        return matches

    def lookup_tickets(
        self,
        employee_id: str | None = None,
        query: str | None = None,
        status: str | None = None,
        ticket_id: str | None = None,
    ) -> list[dict[str, Any]]:
        if os.getenv("USE_LLM_SQL", "false").lower() == "true":
            user_query = query or ""
            if employee_id:
                user_query = f"{user_query} employee_id = '{employee_id.upper()}'".strip()
            if ticket_id:
                user_query = f"{user_query} ticket_id = '{ticket_id.upper()}'".strip()
            if status:
                user_query = f"{user_query} status = '{status}'".strip()
            rows = self._safe_sql_with_llm(user_query or "show recent tickets", "tickets")
            if rows:
                return [
                    {
                        "ticket_id": row.get("ticket_id"),
                        "employee_id": row.get("employee_id"),
                        "title": row.get("title"),
                        "description": row.get("description"),
                        "status": row.get("status"),
                        "category": row.get("category"),
                        "severity": row.get("severity"),
                        "created_at": row.get("created_at"),
                        "updated_at": row.get("updated_at"),
                    }
                    for row in rows
                ]

        sql = "SELECT ticket_id, employee_id, title, description, status, category, severity, created_at, updated_at FROM tickets"
        params: list[Any] = []
        conditions: list[str] = []

        if employee_id:
            conditions.append("employee_id = ?")
            params.append(employee_id.upper())

        if ticket_id:
            conditions.append("ticket_id = ?")
            params.append(ticket_id.upper())

        if status:
            conditions.append("status = ?")
            params.append(status.title())

        if query:
            conditions.append("(LOWER(title) LIKE ? OR LOWER(description) LIKE ? OR LOWER(status) LIKE ?)")
            q = f"%{query.lower()}%"
            params.extend([q, q, q])

        if conditions:
            sql += " WHERE " + " AND ".join(conditions)

        sql += " ORDER BY created_at DESC"

        with self._get_connection() as conn:
            rows = conn.execute(sql, params).fetchall()

        return [
            {
                "ticket_id": row["ticket_id"],
                "employee_id": row["employee_id"],
                "title": row["title"],
                "description": row["description"],
                "status": row["status"],
                "category": row["category"],
                "severity": row["severity"],
                "created_at": row["created_at"],
                "updated_at": row["updated_at"],
            }
            for row in rows
        ]

    def get_ticket_by_id(self, ticket_id: str) -> dict[str, Any] | None:
        tickets = self.lookup_tickets(ticket_id=ticket_id)
        return tickets[0] if tickets else None

    def create_ticket(
        self,
        employee_id: str,
        title: str,
        description: str,
        category: str = "General",
        severity: str = "Medium",
    ) -> dict[str, Any]:
        employee = self.get_employee(employee_id)
        if not employee:
            raise ValueError(f"Employee ID '{employee_id}' was not found.")

        ticket_title = (title or "IT support request").strip()
        ticket_description = (description or "No description provided").strip()

        with self._get_connection() as conn:
            existing = conn.execute(
                "SELECT 1 FROM tickets WHERE employee_id = ? AND LOWER(title) = LOWER(?) LIMIT 1",
                (employee_id.upper(), ticket_title),
            ).fetchone()
            if existing:
                raise ValueError("A similar ticket already exists for this employee.")

            next_number = conn.execute(
                "SELECT CAST(SUBSTR(ticket_id, 4) AS INTEGER) FROM tickets WHERE ticket_id LIKE 'IT-%' ORDER BY CAST(SUBSTR(ticket_id, 4) AS INTEGER) DESC LIMIT 1"
            ).fetchone()

            latest_number = next_number[0] if next_number else 1000
            ticket_id = f"IT-{latest_number + 1}"
            created_at = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S")
            updated_at = created_at

            conn.execute(
                """
                INSERT INTO tickets (ticket_id, employee_id, title, description, status, category, severity, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    ticket_id,
                    employee_id.upper(),
                    ticket_title,
                    ticket_description,
                    "Open",
                    category,
                    severity,
                    created_at,
                    updated_at,
                ),
            )

            conn.execute(
                "INSERT INTO ticket_events (ticket_id, event_type, details, created_at) VALUES (?, ?, ?, ?)",
                (
                    ticket_id,
                    "created",
                    f"Ticket created for employee {employee_id.upper()}",
                    created_at,
                ),
            )

        logger.info("Created ticket %s for employee %s", ticket_id, employee_id)

        return {
            "ticket_id": ticket_id,
            "employee_id": employee_id.upper(),
            "title": ticket_title,
            "description": ticket_description,
            "status": "Open",
            "category": category,
            "severity": severity,
            "created_at": created_at,
            "updated_at": updated_at,
        }

    def update_ticket_status(self, ticket_id: str, status: str, note: str = "") -> dict[str, Any]:
        normalized_status = status.strip().title()
        if normalized_status not in {"Open", "In Progress", "Resolved", "Closed"}:
            raise ValueError(f"Unsupported status '{status}'. Supported statuses: Open, In Progress, Resolved, Closed.")

        with self._get_connection() as conn:
            existing = conn.execute(
                "SELECT ticket_id, employee_id, title, status FROM tickets WHERE ticket_id = ?",
                (ticket_id.upper(),),
            ).fetchone()
            if existing is None:
                raise ValueError(f"Ticket '{ticket_id}' not found.")

            updated_at = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S")
            conn.execute(
                "UPDATE tickets SET status = ?, updated_at = ? WHERE ticket_id = ?",
                (normalized_status, updated_at, ticket_id.upper()),
            )
            conn.execute(
                "INSERT INTO ticket_events (ticket_id, event_type, details, created_at) VALUES (?, ?, ?, ?)",
                (
                    ticket_id.upper(),
                    "status_update",
                    note or f"Status changed from {existing['status']} to {normalized_status}",
                    updated_at,
                ),
            )

        logger.info("Updated ticket %s status to %s", ticket_id, normalized_status)

        ticket = self.get_ticket_by_id(ticket_id.upper())
        if ticket is None:
            raise ValueError(f"Ticket '{ticket_id}' could not be loaded after update.")
        return ticket

    def get_system_status(self, system_name: str | None = None) -> list[dict[str, Any]]:
        if os.getenv("USE_LLM_SQL", "false").lower() == "true":
            query = f"show system status for {system_name or 'all systems'}"
            rows = self._safe_sql_with_llm(query, "system_status")
            if rows:
                return [
                    {
                        "system_name": row.get("system_name"),
                        "status": row.get("status"),
                        "notes": row.get("notes"),
                    }
                    for row in rows
                ]

        with self._get_connection() as conn:
            if system_name:
                rows = conn.execute(
                    "SELECT system_name, status, notes FROM system_status WHERE LOWER(system_name) LIKE ? ORDER BY system_name",
                    (f"%{system_name.lower()}%",),
                ).fetchall()
            else:
                rows = conn.execute("SELECT system_name, status, notes FROM system_status ORDER BY system_name").fetchall()

        return [
            {
                "system_name": row["system_name"],
                "status": row["status"],
                "notes": row["notes"],
            }
            for row in rows
        ]

    def get_dashboard_summary(self) -> dict[str, Any]:
        with self._get_connection() as conn:
            totals = conn.execute(
                "SELECT status, COUNT(*) as total FROM tickets GROUP BY status ORDER BY status"
            ).fetchall()
            open_tickets = conn.execute("SELECT COUNT(*) FROM tickets WHERE status IN ('Open', 'In Progress')").fetchone()[0]
            system_summary = conn.execute("SELECT system_name, status FROM system_status").fetchall()

        return {
            "ticket_status_counts": {row["status"]: row["total"] for row in totals},
            "open_ticket_count": open_tickets,
            "system_status": [
                {"system_name": row["system_name"], "status": row["status"]} for row in system_summary
            ],
        }

    def get_ticket_history(self, ticket_id: str) -> list[dict[str, Any]]:
        with self._get_connection() as conn:
            rows = conn.execute(
                "SELECT event_type, details, created_at FROM ticket_events WHERE ticket_id = ? ORDER BY created_at DESC",
                (ticket_id.upper(),),
            ).fetchall()

        return [
            {
                "event_type": row["event_type"],
                "details": row["details"],
                "created_at": row["created_at"],
            }
            for row in rows
        ]

    def get_employee_role(self, employee_id: str | None) -> str:
        if not employee_id:
            return "employee"
        employee = self.get_employee(employee_id)
        return (employee or {}).get("role", "employee").lower()

    def add_ticket_comment(self, ticket_id: str, employee_id: str, comment: str) -> dict[str, Any]:
        ticket = self.get_ticket_by_id(ticket_id)
        if ticket is None:
            raise ValueError(f"Ticket '{ticket_id}' not found.")

        trimmed_comment = (comment or "").strip()
        if not trimmed_comment:
            raise ValueError("Comment cannot be empty.")

        created_at = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S")
        with self._get_connection() as conn:
            conn.execute(
                "INSERT INTO ticket_comments (ticket_id, employee_id, comment, created_at) VALUES (?, ?, ?, ?)",
                (ticket_id.upper(), employee_id.upper(), trimmed_comment, created_at),
            )
            conn.execute(
                "INSERT INTO ticket_events (ticket_id, event_type, details, created_at) VALUES (?, ?, ?, ?)",
                (
                    ticket_id.upper(),
                    "comment",
                    f"Comment added by {employee_id.upper()}: {trimmed_comment}",
                    created_at,
                ),
            )

        logger.info("Added comment to ticket %s by %s", ticket_id, employee_id)

        return {
            "ticket_id": ticket_id.upper(),
            "employee_id": employee_id.upper(),
            "comment": trimmed_comment,
            "created_at": created_at,
        }

    def get_ticket_comments(self, ticket_id: str) -> list[dict[str, Any]]:
        with self._get_connection() as conn:
            rows = conn.execute(
                "SELECT employee_id, comment, created_at FROM ticket_comments WHERE ticket_id = ? ORDER BY created_at DESC",
                (ticket_id.upper(),),
            ).fetchall()

        return [
            {
                "employee_id": row["employee_id"],
                "comment": row["comment"],
                "created_at": row["created_at"],
            }
            for row in rows
        ]

    def list_recent_tickets(self, limit: int = 5) -> list[dict[str, Any]]:
        with self._get_connection() as conn:
            rows = conn.execute(
                "SELECT ticket_id, employee_id, title, description, status, category, severity, created_at, updated_at FROM tickets ORDER BY updated_at DESC LIMIT ?",
                (limit,),
            ).fetchall()

        return [
            {
                "ticket_id": row["ticket_id"],
                "employee_id": row["employee_id"],
                "title": row["title"],
                "description": row["description"],
                "status": row["status"],
                "category": row["category"],
                "severity": row["severity"],
                "created_at": row["created_at"],
                "updated_at": row["updated_at"],
            }
            for row in rows
        ]
